exports.greetings = [  'oi',
  'oy',
  'oyy',
  'oii',
  'oiii',
  'oi brow',
  'oyy',
  'oyyy',
  'olááá',
  'olá',
  'olá!',
  'oláá',
  'ollá',
  'oláá!',
  'ollá',
  'holá',
  'hollá',
  'hola',
  'olaa',
  'olla',
  'ola',
  'ola!',
  'kmk',
  'kmk brow',
  'kmk man',
  'kmk mano',
  'kmk?',
  'kmk brow?',
  'kmk man?',
  'kmk mano?',
  'kmk boss',
  'kmk boss?',
  'kmk chefe',
  'kmk chefe?',
  'kmk chefia?',
  'kmk chefia',
  'kmkie',
  'iai',
  'e ai mano',          
  'kml',           // Como é que levas?
  'qual é a cena',
  'kuala cena',
  'kual é a cena',
  'kualé',
  'tá-se',
  'tudo nice?',
  'tudo fixe?',
  'como tá?',
  'como é?',
  'como é que é?',
  'ya',
  'yoo',
  'yoh',
  'yo',
  'yolo',
  'yap',
  'yop',
  'yeh',
  'yeeh',
  'yebo',
  'yala',
  'yap',
  'boas',
  'fala',
  'tá bué?',
  'tá tranquilo?',
  'tá firme?',
  'tá tudo?',
  'tá na boa?',
  'tá-se bem?',
  'tá-se fixe?',
  'presente',
  'cheguei',
  'bora lá',

  'csm',
  'csm bot',

  'Boa tarde',
  'boa tarde!',
  'boa noite',
  'boa noite!',
  'bom dia',
  'bom dia!',]

  exports.respostasSaudacao = {
  'oi': 'Oi oi! Tudo nice contigo?',
  'oy': 'Oy! Como tá a cena aí?',
  'oyy': 'Oyyy! Tamos juntos!',
  'oyyy': 'Oyyy! Já tava com saudades 😄',
  'olá': 'Olá! Tudo tranquilo por aí?',
  'olá!': 'Olá! Tudo tranquilo por aí?',
  'kmk': 'Tá nice, e contigo?',
  'kml': 'Levo bem, e tu como levas?',
  'qual é a cena': 'A cena tá boa! E aí, qual é a tua?',
  'kuala cena': 'Tudo tranquilo! Qual é a cena aí?',
  'kual é a cena': 'Tá-se bem! Qual é a cena por aí?',
  'kualé': 'Kualé! Tudo bué?',
  'tá-se': 'Tá-se fixe! Bora conversar!',
  'tudo nice?': 'Tudo nice sim! E contigo?',
  'tudo fixe?': 'Fixe como sempre! E tu?',
  'como tá?': 'Tá firme! E aí, como tá contigo?',
  'como é?': 'É tudo! Como é que é aí?',
  'como é que é?': 'Tudo tranquilo! Como é que é por aí?',
  'ya': 'Ya ya! Tamos juntos!',
  'yo': 'Yo! Qual é a vibe?',
  'como vai?': 'Vou bem! E aí, como vai?',
  'como está': 'É tudo! Como é que é aí?',
  'como é que é?': 'Tudo tranquilo! Como é que é por aí?',
  'como vai': 'Vou bem! E aí, como vai?',
  'como estás': 'É tudo! Como é que é aí?',
  'como é que estás?': 'Tudo tranquilo! Como é que é por aí?',
  'como é que está?': 'Estou bem! e ai?',
  'fala': 'Fala aí! Tô na escuta!',
  'tá bué?': 'Tá bué sim! E aí, tá firme?',
  'tá tranquilo?': 'Tranquilo como sempre! E tu?',
  'tá firme?': 'Firmeza total! Como tá aí?',
  'tá tudo?': 'Tá tudo sim! E contigo?',
  'tá na boa?': 'Na boa sempre! Bora lá!',
  'tá-se bem?': 'Tá-se bem! Tamos juntos!',
  'tá-se fixe?': 'Fixe como sempre! Qual é a cena?',
  'presente': 'Presença confirmada! 😎',
  'cheguei': 'Chegaste bem! Bora nessa!',
  'bora lá': 'Bora lá sim! Tô contigo!',
  'partiu conversa': 'Partiu! Tô pronto pra trocar ideia!',
  'tamos juntos': 'Sempre! Tamos juntos nessa!',
  'csm bot': 'Presença confirmada!',
  'csm': 'CSM eh a empresa que me mantem e mantem a plataforma de vendas e compras',

  'oy': 'Oy! Tudo nice por aí?',
  'oyy': 'Oyy! Qual é a cena hoje?',
  'oyyy': 'Oyyy! Já tava à tua espera 😄',
  'olá': 'Olá! Tudo tranquilo?',
  'olááá': 'Olááá! Energia boa aí, né?',
  'ollá': 'Ollá! Tamos juntos!',
  'holá': 'Holá! Como tá a vibe?',
  'hollá': 'Hollá! Tudo bué?',
  'hola': 'Hola! Tá-se bem?',
  'olaa': 'Olaa! Bora nessa!',
  'olla': 'Olla! Tudo firme?',
  'ola': 'Ola! Como é que tá?',
  'ola!': 'Ola! Como é que tá?',
  'kmk': 'Tá nice, e contigo?',
  'kmkie': 'Tudo tranquilo! E tu, kmkie?',
  'iai': 'Iai mano! Tudo na paz?',
  'e ai mano': 'E aí mano! Qual é a cena?',
  'kml': 'Levo bem! E tu, como levas?',
  'qual é a cena': 'A cena tá boa! E aí, qual é a tua?',
  'kuala cena': 'Tudo tranquilo! Kuala cena aí?',
  'kual é a cena': 'Tá-se bem! Kual é a cena por aí?',
  'kualé': 'Kualé! Tamos juntos!',
  'tá-se': 'Tá-se fixe! Bora conversar!',
  'tudo nice?': 'Nice como sempre! E contigo?',
  'tudo fixe?': 'Fixe total! Qual é a cena?',
  'como tá?': 'Tá firme! E aí, como tá contigo?',
  'como é?': 'É tudo! Como é que é aí?',
  'como é que é?': 'Tudo tranquilo! Como é que é por aí?',
  'ya': 'Ya ya! Tamos juntos!',
  'yoo': 'Yoo! Qual é a vibe?',
  'yoh': 'Yoh mano! Tudo bué?',
  'yo': 'Yo! Bora nessa!',
  'yolo': 'YOLO! Então vamos viver essa conversa 😄',
  'yap': 'Yap! Tô na escuta!',
  'yop': 'Yop! Tudo firme?',
  'yeh': 'Yeh! Tá tudo nice?',
  'yeeh': 'Yeeh! Energia positiva!',
  'yebo': 'Yebo! Tamos aí!',
  'yala': 'Yala! Partiu conversa!',

  'Boa tarde': 'Oi, boa tarde!',
  'boa tarde!': 'Oi, boa tarde!',
  'boa noite': 'Oi, boa noite',
  'boa noite!': 'Oi boa noite',
  'bom dia': 'oi, bom dia',
  'bom dia!': 'Oi, bom dia'
};


exports.aboutCMDS = ['quero saber mais',
    'me fale mais',
    'como funciona',
    'como funciona?',
    'info',
    'sobre',
    'sobre o sistema',
    'saber mais',
    'super compras',
    'me fale da loja',
    'loja',
    'quero saber mais',
    'Sobre a plataforma',
    '1',
    '1.',
    '1-',
    '1 - ',
    '1 -'

]

exports.botVersion = 1.1

exports.GEMINI_API_KEY = 'AIzaSyDiCNopMFQse_vqXfGO5IyOcyTlXwm6emM'