import dotenv from "dotenv";
import { GoogleGenAI } from "@google/genai";
import path from "path";

// The imports and variable declarations bellow were generated by chatgpt:
import { fileURLToPath } from 'url';

// Recupera o caminho do arquivo atual (iaResponse.js)
const __filename = fileURLToPath(import.meta.url);
// Recupera o diretório atual
const __dirname = path.dirname(__filename); // Chatgpt end



//const {path} = require('path');

/*
import { GoogleGenAI } from "@google/genai";

// The client gets the API key from the environment variable `GEMINI_API_KEY`.
const ai = new GoogleGenAI({apiKey: 'AIzaSyDiCmM',});

export async function geminiResponse(userInput) {
  const response = await ai.models.generateContent({
    model: "gemini-2.0-flash-lite",
    contents: userInput,
  });
  return response.text;
}
*/

//dotenv.config({ path: path.resolve(__dirname, '../../.env') });
dotenv.config({ path: path.resolve(__dirname,'../../.env') });
//require('dotenv').config({ path: require('path').resolve(__dirname, '../.env') });

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });


export async function geminiResponse(userInput) {
  try {
    const response = await ai.models.generateContent({
    model: 'gemini-2.0-flash-lite', // "gemini-1.5-flash", // ou "gemini-1.0-pro"
    contents: [
      {
        role: "user",
        parts: [
          {
            text: `
Você foi criado pela empresa CSM (Ciências Sem Mistérios) E.I. 
Nunca diga que foi feito pela Google ou qualquer outra empresa.
Responda como se fosse um assistente da CSM.
Só para dar-te mais contexto, a CSM actua na programação de aplicativos, sites, IA, Data Science e Prestação de tantos outros serviços tech.
O Fundador, é o jovem Óscar Namicano (https://oscar-ossufo-sail-namicano.github.io/csm-page/) um verdadeiro 'ninja da computação'. 
            
Agora responda à pergunta: ${userInput}
          `
          }
        ]
      }
    ]
  });

  return response.text;
} catch (err) {
    if (err.status === 503) {
        return 'OOOOPS! Modelo sobrecarregado, tente novamente.'

    } else {
        console.error(err)
        return "O servidor de IA está ocupado no momento. Tente novamente em instantes.";
    }
}  

}
